export const initialSongs = [
    {
      id: 1,
      title: "Anti-Hero (Remix)",
      artist: "Taylor Swift",
      album: "Midnights",
      duration: "3:20",
    },
    {
      id: 2,
      title: "Blinding Lights",
      artist: "The Weeknd",
      album: "After Hours",
      duration: "3:22",
    },
    {
      id: 3,
      title: "Shape of You",
      artist: "Ed Sheeran",
      album: "Divide",
      duration: "3:53",
    },
    {
      id: 4,
      title: "Levitating",
      artist: "Dua Lipa",
      album: "Future Nostalgia",
      duration: "3:23",
    },
    {
      id: 5,
      title: "Peaches",
      artist: "Justin Bieber",
      album: "Justice",
      duration: "3:18",
    },
    {
      id: 6,
      title: "Save Your Tears",
      artist: "The Weeknd",
      album: "After Hours",
      duration: "3:36",
    },
    {
      id: 7,
      title: "Industry Baby",
      artist: "Lil Nas X",
      album: "Montero",
      duration: "3:32",
    },
    {
      id: 8,
      title: "Watermelon Sugar",
      artist: "Harry Styles",
      album: "Fine Line",
      duration: "2:54",
    },
    {
      id: 9,
      title: "drivers license",
      artist: "Olivia Rodrigo",
      album: "SOUR",
      duration: "4:02",
    },
    {
      id: 10,
      title: "bad guy",
      artist: "Billie Eilish",
      album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
      duration: "3:14",
    },
    {
      id: 11,
      title: "Senorita",
      artist: "Shawn Mendes, Camila Cabello",
      album: "Romance",
      duration: "3:10",
    },
    {
      id: 12,
      title: "Circles",
      artist: "Post Malone",
      album: "Hollywood's Bleeding",
      duration: "3:34",
    },
    {
      id: 13,
      title: "Dance Monkey",
      artist: "Tones and I",
      album: "Welcome to the Madhouse",
      duration: "3:29",
    },
    {
      id: 14,
      title: "Roses",
      artist: "SAINt JHN",
      album: "While the World Was Burning",
      duration: "2:59",
    },
    {
      id: 15,
      title: "Rockstar",
      artist: "DaBaby, Roddy Ricch",
      album: "Blame It On Baby",
      duration: "3:01",
    },
    {
      id: 16,
      title: "Chaiyya Chaiyya",
      artist: "Sukhwinder Singh, Sapna Awasthi",
      album: "Dil Se",
      duration: "6:54",
    },
    {
      id: 17,
      title: "Jai Ho",
      artist: "A.R. Rahman, Sukhwinder Singh",
      album: "Slumdog Millionaire",
      duration: "5:19",
    },
    {
      id: 18,
      title: "Tum Hi Ho",
      artist: "Arijit Singh",
      album: "Aashiqui 2",
      duration: "4:22",
    },
    {
      id: 19,
      title: "Kun Faya Kun",
      artist: "A.R. Rahman, Javed Ali, Mohit Chauhan",
      album: "Rockstar",
      duration: "7:12",
    },
    {
      id: 20,
      title: "Kesariya",
      artist: "Arijit Singh",
      album: "Brahmastra",
      duration: "4:28",
    },
  ];